// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/chunk_master/chunk_master.proto

package chunk_master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkMasterService_ReportChunk_FullMethodName  = "/gfs.chunk_master.ChunkMasterService/ReportChunk"
	ChunkMasterService_RequestLease_FullMethodName = "/gfs.chunk_master.ChunkMasterService/RequestLease"
	ChunkMasterService_HeartBeat_FullMethodName    = "/gfs.chunk_master.ChunkMasterService/HeartBeat"
)

// ChunkMasterServiceClient is the client API for ChunkMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkMasterServiceClient interface {
	// For reporting all the hosted chunks to the master on (chunk server) startup
	ReportChunk(ctx context.Context, in *ReportChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReportChunkResponse], error)
	RequestLease(ctx context.Context, in *RequestLeaseRequest, opts ...grpc.CallOption) (*RequestLeaseResponse, error)
	HeartBeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartBeatRequest, HeartBeatResponse], error)
}

type chunkMasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkMasterServiceClient(cc grpc.ClientConnInterface) ChunkMasterServiceClient {
	return &chunkMasterServiceClient{cc}
}

func (c *chunkMasterServiceClient) ReportChunk(ctx context.Context, in *ReportChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReportChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkMasterService_ServiceDesc.Streams[0], ChunkMasterService_ReportChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportChunkRequest, ReportChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkMasterService_ReportChunkClient = grpc.ServerStreamingClient[ReportChunkResponse]

func (c *chunkMasterServiceClient) RequestLease(ctx context.Context, in *RequestLeaseRequest, opts ...grpc.CallOption) (*RequestLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestLeaseResponse)
	err := c.cc.Invoke(ctx, ChunkMasterService_RequestLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkMasterServiceClient) HeartBeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartBeatRequest, HeartBeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkMasterService_ServiceDesc.Streams[1], ChunkMasterService_HeartBeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartBeatRequest, HeartBeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkMasterService_HeartBeatClient = grpc.BidiStreamingClient[HeartBeatRequest, HeartBeatResponse]

// ChunkMasterServiceServer is the server API for ChunkMasterService service.
// All implementations must embed UnimplementedChunkMasterServiceServer
// for forward compatibility.
type ChunkMasterServiceServer interface {
	// For reporting all the hosted chunks to the master on (chunk server) startup
	ReportChunk(*ReportChunkRequest, grpc.ServerStreamingServer[ReportChunkResponse]) error
	RequestLease(context.Context, *RequestLeaseRequest) (*RequestLeaseResponse, error)
	HeartBeat(grpc.BidiStreamingServer[HeartBeatRequest, HeartBeatResponse]) error
	mustEmbedUnimplementedChunkMasterServiceServer()
}

// UnimplementedChunkMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkMasterServiceServer struct{}

func (UnimplementedChunkMasterServiceServer) ReportChunk(*ReportChunkRequest, grpc.ServerStreamingServer[ReportChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportChunk not implemented")
}
func (UnimplementedChunkMasterServiceServer) RequestLease(context.Context, *RequestLeaseRequest) (*RequestLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestLease not implemented")
}
func (UnimplementedChunkMasterServiceServer) HeartBeat(grpc.BidiStreamingServer[HeartBeatRequest, HeartBeatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedChunkMasterServiceServer) mustEmbedUnimplementedChunkMasterServiceServer() {}
func (UnimplementedChunkMasterServiceServer) testEmbeddedByValue()                            {}

// UnsafeChunkMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkMasterServiceServer will
// result in compilation errors.
type UnsafeChunkMasterServiceServer interface {
	mustEmbedUnimplementedChunkMasterServiceServer()
}

func RegisterChunkMasterServiceServer(s grpc.ServiceRegistrar, srv ChunkMasterServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkMasterService_ServiceDesc, srv)
}

func _ChunkMasterService_ReportChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReportChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkMasterServiceServer).ReportChunk(m, &grpc.GenericServerStream[ReportChunkRequest, ReportChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkMasterService_ReportChunkServer = grpc.ServerStreamingServer[ReportChunkResponse]

func _ChunkMasterService_RequestLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkMasterServiceServer).RequestLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkMasterService_RequestLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkMasterServiceServer).RequestLease(ctx, req.(*RequestLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkMasterService_HeartBeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkMasterServiceServer).HeartBeat(&grpc.GenericServerStream[HeartBeatRequest, HeartBeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkMasterService_HeartBeatServer = grpc.BidiStreamingServer[HeartBeatRequest, HeartBeatResponse]

// ChunkMasterService_ServiceDesc is the grpc.ServiceDesc for ChunkMasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkMasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gfs.chunk_master.ChunkMasterService",
	HandlerType: (*ChunkMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestLease",
			Handler:    _ChunkMasterService_RequestLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportChunk",
			Handler:       _ChunkMasterService_ReportChunk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HeartBeat",
			Handler:       _ChunkMasterService_HeartBeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/chunk_master/chunk_master.proto",
}
