// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/chunk/chunk.proto

package chunk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkService_PushData_FullMethodName                   = "/gfs.chunk.ChunkService/PushData"
	ChunkService_ForwardWriteChunk_FullMethodName          = "/gfs.chunk.ChunkService/ForwardWriteChunk"
	ChunkService_ForwardAppendChunkPhaseOne_FullMethodName = "/gfs.chunk.ChunkService/ForwardAppendChunkPhaseOne"
	ChunkService_ForwardAppendChunkPhaseTwo_FullMethodName = "/gfs.chunk.ChunkService/ForwardAppendChunkPhaseTwo"
	ChunkService_ForwardAppendChunkNullify_FullMethodName  = "/gfs.chunk.ChunkService/ForwardAppendChunkNullify"
	ChunkService_ForwardReplicateChunk_FullMethodName      = "/gfs.chunk.ChunkService/ForwardReplicateChunk"
)

// ChunkServiceClient is the client API for ChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServiceClient interface {
	PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, PushDataResponse], error)
	ForwardWriteChunk(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error)
	ForwardAppendChunkPhaseOne(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error)
	ForwardAppendChunkPhaseTwo(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error)
	ForwardAppendChunkNullify(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error)
	ForwardReplicateChunk(ctx context.Context, in *ForwardReplicateChunkRequest, opts ...grpc.CallOption) (*ForwardReplicateChunkResponse, error)
}

type chunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServiceClient(cc grpc.ClientConnInterface) ChunkServiceClient {
	return &chunkServiceClient{cc}
}

func (c *chunkServiceClient) PushData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, PushDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkService_ServiceDesc.Streams[0], ChunkService_PushData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, PushDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_PushDataClient = grpc.ClientStreamingClient[DataChunk, PushDataResponse]

func (c *chunkServiceClient) ForwardWriteChunk(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWriteResponse)
	err := c.cc.Invoke(ctx, ChunkService_ForwardWriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) ForwardAppendChunkPhaseOne(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWriteResponse)
	err := c.cc.Invoke(ctx, ChunkService_ForwardAppendChunkPhaseOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) ForwardAppendChunkPhaseTwo(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWriteResponse)
	err := c.cc.Invoke(ctx, ChunkService_ForwardAppendChunkPhaseTwo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) ForwardAppendChunkNullify(ctx context.Context, in *ForwardAppendRequest, opts ...grpc.CallOption) (*ForwardWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWriteResponse)
	err := c.cc.Invoke(ctx, ChunkService_ForwardAppendChunkNullify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServiceClient) ForwardReplicateChunk(ctx context.Context, in *ForwardReplicateChunkRequest, opts ...grpc.CallOption) (*ForwardReplicateChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardReplicateChunkResponse)
	err := c.cc.Invoke(ctx, ChunkService_ForwardReplicateChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServiceServer is the server API for ChunkService service.
// All implementations must embed UnimplementedChunkServiceServer
// for forward compatibility.
type ChunkServiceServer interface {
	PushData(grpc.ClientStreamingServer[DataChunk, PushDataResponse]) error
	ForwardWriteChunk(context.Context, *ForwardWriteRequest) (*ForwardWriteResponse, error)
	ForwardAppendChunkPhaseOne(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error)
	ForwardAppendChunkPhaseTwo(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error)
	ForwardAppendChunkNullify(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error)
	ForwardReplicateChunk(context.Context, *ForwardReplicateChunkRequest) (*ForwardReplicateChunkResponse, error)
	mustEmbedUnimplementedChunkServiceServer()
}

// UnimplementedChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServiceServer struct{}

func (UnimplementedChunkServiceServer) PushData(grpc.ClientStreamingServer[DataChunk, PushDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedChunkServiceServer) ForwardWriteChunk(context.Context, *ForwardWriteRequest) (*ForwardWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardWriteChunk not implemented")
}
func (UnimplementedChunkServiceServer) ForwardAppendChunkPhaseOne(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardAppendChunkPhaseOne not implemented")
}
func (UnimplementedChunkServiceServer) ForwardAppendChunkPhaseTwo(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardAppendChunkPhaseTwo not implemented")
}
func (UnimplementedChunkServiceServer) ForwardAppendChunkNullify(context.Context, *ForwardAppendRequest) (*ForwardWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardAppendChunkNullify not implemented")
}
func (UnimplementedChunkServiceServer) ForwardReplicateChunk(context.Context, *ForwardReplicateChunkRequest) (*ForwardReplicateChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardReplicateChunk not implemented")
}
func (UnimplementedChunkServiceServer) mustEmbedUnimplementedChunkServiceServer() {}
func (UnimplementedChunkServiceServer) testEmbeddedByValue()                      {}

// UnsafeChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServiceServer will
// result in compilation errors.
type UnsafeChunkServiceServer interface {
	mustEmbedUnimplementedChunkServiceServer()
}

func RegisterChunkServiceServer(s grpc.ServiceRegistrar, srv ChunkServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkService_ServiceDesc, srv)
}

func _ChunkService_PushData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkServiceServer).PushData(&grpc.GenericServerStream[DataChunk, PushDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkService_PushDataServer = grpc.ClientStreamingServer[DataChunk, PushDataResponse]

func _ChunkService_ForwardWriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ForwardWriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ForwardWriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ForwardWriteChunk(ctx, req.(*ForwardWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_ForwardAppendChunkPhaseOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ForwardAppendChunkPhaseOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ForwardAppendChunkPhaseOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ForwardAppendChunkPhaseOne(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_ForwardAppendChunkPhaseTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ForwardAppendChunkPhaseTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ForwardAppendChunkPhaseTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ForwardAppendChunkPhaseTwo(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_ForwardAppendChunkNullify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ForwardAppendChunkNullify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ForwardAppendChunkNullify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ForwardAppendChunkNullify(ctx, req.(*ForwardAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkService_ForwardReplicateChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardReplicateChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServiceServer).ForwardReplicateChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkService_ForwardReplicateChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServiceServer).ForwardReplicateChunk(ctx, req.(*ForwardReplicateChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkService_ServiceDesc is the grpc.ServiceDesc for ChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gfs.chunk.ChunkService",
	HandlerType: (*ChunkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardWriteChunk",
			Handler:    _ChunkService_ForwardWriteChunk_Handler,
		},
		{
			MethodName: "ForwardAppendChunkPhaseOne",
			Handler:    _ChunkService_ForwardAppendChunkPhaseOne_Handler,
		},
		{
			MethodName: "ForwardAppendChunkPhaseTwo",
			Handler:    _ChunkService_ForwardAppendChunkPhaseTwo_Handler,
		},
		{
			MethodName: "ForwardAppendChunkNullify",
			Handler:    _ChunkService_ForwardAppendChunkNullify_Handler,
		},
		{
			MethodName: "ForwardReplicateChunk",
			Handler:    _ChunkService_ForwardReplicateChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushData",
			Handler:       _ChunkService_PushData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/chunk/chunk.proto",
}
