// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/chunk_operations/chunk_operations.proto

package chunk_operations

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkOperationService_WriteChunk_FullMethodName        = "/gfs.chunk_operations.ChunkOperationService/WriteChunk"
	ChunkOperationService_ReadChunk_FullMethodName         = "/gfs.chunk_operations.ChunkOperationService/ReadChunk"
	ChunkOperationService_RecordAppendChunk_FullMethodName = "/gfs.chunk_operations.ChunkOperationService/RecordAppendChunk"
	ChunkOperationService_PushDataToPrimary_FullMethodName = "/gfs.chunk_operations.ChunkOperationService/PushDataToPrimary"
)

// ChunkOperationServiceClient is the client API for ChunkOperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkOperationServiceClient interface {
	WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	RecordAppendChunk(ctx context.Context, in *RecordAppendChunkRequest, opts ...grpc.CallOption) (*RecordAppendChunkResponse, error)
	PushDataToPrimary(ctx context.Context, in *PushDataToPrimaryRequest, opts ...grpc.CallOption) (*PushDataToPrimaryResponse, error)
}

type chunkOperationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkOperationServiceClient(cc grpc.ClientConnInterface) ChunkOperationServiceClient {
	return &chunkOperationServiceClient{cc}
}

func (c *chunkOperationServiceClient) WriteChunk(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkOperationService_WriteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkOperationServiceClient) ReadChunk(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkOperationService_ReadChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkOperationServiceClient) RecordAppendChunk(ctx context.Context, in *RecordAppendChunkRequest, opts ...grpc.CallOption) (*RecordAppendChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAppendChunkResponse)
	err := c.cc.Invoke(ctx, ChunkOperationService_RecordAppendChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkOperationServiceClient) PushDataToPrimary(ctx context.Context, in *PushDataToPrimaryRequest, opts ...grpc.CallOption) (*PushDataToPrimaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushDataToPrimaryResponse)
	err := c.cc.Invoke(ctx, ChunkOperationService_PushDataToPrimary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkOperationServiceServer is the server API for ChunkOperationService service.
// All implementations must embed UnimplementedChunkOperationServiceServer
// for forward compatibility.
type ChunkOperationServiceServer interface {
	WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	RecordAppendChunk(context.Context, *RecordAppendChunkRequest) (*RecordAppendChunkResponse, error)
	PushDataToPrimary(context.Context, *PushDataToPrimaryRequest) (*PushDataToPrimaryResponse, error)
	mustEmbedUnimplementedChunkOperationServiceServer()
}

// UnimplementedChunkOperationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkOperationServiceServer struct{}

func (UnimplementedChunkOperationServiceServer) WriteChunk(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteChunk not implemented")
}
func (UnimplementedChunkOperationServiceServer) ReadChunk(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedChunkOperationServiceServer) RecordAppendChunk(context.Context, *RecordAppendChunkRequest) (*RecordAppendChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordAppendChunk not implemented")
}
func (UnimplementedChunkOperationServiceServer) PushDataToPrimary(context.Context, *PushDataToPrimaryRequest) (*PushDataToPrimaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushDataToPrimary not implemented")
}
func (UnimplementedChunkOperationServiceServer) mustEmbedUnimplementedChunkOperationServiceServer() {}
func (UnimplementedChunkOperationServiceServer) testEmbeddedByValue()                               {}

// UnsafeChunkOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkOperationServiceServer will
// result in compilation errors.
type UnsafeChunkOperationServiceServer interface {
	mustEmbedUnimplementedChunkOperationServiceServer()
}

func RegisterChunkOperationServiceServer(s grpc.ServiceRegistrar, srv ChunkOperationServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkOperationService_ServiceDesc, srv)
}

func _ChunkOperationService_WriteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkOperationServiceServer).WriteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkOperationService_WriteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkOperationServiceServer).WriteChunk(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkOperationService_ReadChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkOperationServiceServer).ReadChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkOperationService_ReadChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkOperationServiceServer).ReadChunk(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkOperationService_RecordAppendChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAppendChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkOperationServiceServer).RecordAppendChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkOperationService_RecordAppendChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkOperationServiceServer).RecordAppendChunk(ctx, req.(*RecordAppendChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkOperationService_PushDataToPrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDataToPrimaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkOperationServiceServer).PushDataToPrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkOperationService_PushDataToPrimary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkOperationServiceServer).PushDataToPrimary(ctx, req.(*PushDataToPrimaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkOperationService_ServiceDesc is the grpc.ServiceDesc for ChunkOperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkOperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gfs.chunk_operations.ChunkOperationService",
	HandlerType: (*ChunkOperationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteChunk",
			Handler:    _ChunkOperationService_WriteChunk_Handler,
		},
		{
			MethodName: "ReadChunk",
			Handler:    _ChunkOperationService_ReadChunk_Handler,
		},
		{
			MethodName: "RecordAppendChunk",
			Handler:    _ChunkOperationService_RecordAppendChunk_Handler,
		},
		{
			MethodName: "PushDataToPrimary",
			Handler:    _ChunkOperationService_PushDataToPrimary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/chunk_operations/chunk_operations.proto",
}
