// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/client_master/client_master.proto

package client_master

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientMasterService_GetFileChunksInfo_FullMethodName       = "/gfs.client_master.ClientMasterService/GetFileChunksInfo"
	ClientMasterService_GetLastChunkIndexInFile_FullMethodName = "/gfs.client_master.ClientMasterService/GetLastChunkIndexInFile"
	ClientMasterService_CreateFile_FullMethodName              = "/gfs.client_master.ClientMasterService/CreateFile"
	ClientMasterService_DeleteFile_FullMethodName              = "/gfs.client_master.ClientMasterService/DeleteFile"
	ClientMasterService_UndeleteFile_FullMethodName            = "/gfs.client_master.ClientMasterService/UndeleteFile"
	ClientMasterService_RenameFile_FullMethodName              = "/gfs.client_master.ClientMasterService/RenameFile"
)

// ClientMasterServiceClient is the client API for ClientMasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientMasterServiceClient interface {
	GetFileChunksInfo(ctx context.Context, in *GetFileChunksInfoRequest, opts ...grpc.CallOption) (*GetFileChunksInfoResponse, error)
	// Get the last file chunk related to a file
	GetLastChunkIndexInFile(ctx context.Context, in *GetLastChunkIndexInFileRequest, opts ...grpc.CallOption) (*GetLastChunkIndexInFileResponse, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	UndeleteFile(ctx context.Context, in *UndeleteFileRequest, opts ...grpc.CallOption) (*UndeleteFileResponse, error)
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
}

type clientMasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientMasterServiceClient(cc grpc.ClientConnInterface) ClientMasterServiceClient {
	return &clientMasterServiceClient{cc}
}

func (c *clientMasterServiceClient) GetFileChunksInfo(ctx context.Context, in *GetFileChunksInfoRequest, opts ...grpc.CallOption) (*GetFileChunksInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileChunksInfoResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_GetFileChunksInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientMasterServiceClient) GetLastChunkIndexInFile(ctx context.Context, in *GetLastChunkIndexInFileRequest, opts ...grpc.CallOption) (*GetLastChunkIndexInFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastChunkIndexInFileResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_GetLastChunkIndexInFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientMasterServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientMasterServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientMasterServiceClient) UndeleteFile(ctx context.Context, in *UndeleteFileRequest, opts ...grpc.CallOption) (*UndeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteFileResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_UndeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientMasterServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, ClientMasterService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientMasterServiceServer is the server API for ClientMasterService service.
// All implementations must embed UnimplementedClientMasterServiceServer
// for forward compatibility.
type ClientMasterServiceServer interface {
	GetFileChunksInfo(context.Context, *GetFileChunksInfoRequest) (*GetFileChunksInfoResponse, error)
	// Get the last file chunk related to a file
	GetLastChunkIndexInFile(context.Context, *GetLastChunkIndexInFileRequest) (*GetLastChunkIndexInFileResponse, error)
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	UndeleteFile(context.Context, *UndeleteFileRequest) (*UndeleteFileResponse, error)
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	mustEmbedUnimplementedClientMasterServiceServer()
}

// UnimplementedClientMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientMasterServiceServer struct{}

func (UnimplementedClientMasterServiceServer) GetFileChunksInfo(context.Context, *GetFileChunksInfoRequest) (*GetFileChunksInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileChunksInfo not implemented")
}
func (UnimplementedClientMasterServiceServer) GetLastChunkIndexInFile(context.Context, *GetLastChunkIndexInFileRequest) (*GetLastChunkIndexInFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastChunkIndexInFile not implemented")
}
func (UnimplementedClientMasterServiceServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedClientMasterServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedClientMasterServiceServer) UndeleteFile(context.Context, *UndeleteFileRequest) (*UndeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteFile not implemented")
}
func (UnimplementedClientMasterServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedClientMasterServiceServer) mustEmbedUnimplementedClientMasterServiceServer() {}
func (UnimplementedClientMasterServiceServer) testEmbeddedByValue()                             {}

// UnsafeClientMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientMasterServiceServer will
// result in compilation errors.
type UnsafeClientMasterServiceServer interface {
	mustEmbedUnimplementedClientMasterServiceServer()
}

func RegisterClientMasterServiceServer(s grpc.ServiceRegistrar, srv ClientMasterServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientMasterService_ServiceDesc, srv)
}

func _ClientMasterService_GetFileChunksInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileChunksInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).GetFileChunksInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_GetFileChunksInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).GetFileChunksInfo(ctx, req.(*GetFileChunksInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientMasterService_GetLastChunkIndexInFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastChunkIndexInFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).GetLastChunkIndexInFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_GetLastChunkIndexInFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).GetLastChunkIndexInFile(ctx, req.(*GetLastChunkIndexInFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientMasterService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientMasterService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientMasterService_UndeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).UndeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_UndeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).UndeleteFile(ctx, req.(*UndeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientMasterService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientMasterServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientMasterService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientMasterServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientMasterService_ServiceDesc is the grpc.ServiceDesc for ClientMasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientMasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gfs.client_master.ClientMasterService",
	HandlerType: (*ClientMasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileChunksInfo",
			Handler:    _ClientMasterService_GetFileChunksInfo_Handler,
		},
		{
			MethodName: "GetLastChunkIndexInFile",
			Handler:    _ClientMasterService_GetLastChunkIndexInFile_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _ClientMasterService_CreateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _ClientMasterService_DeleteFile_Handler,
		},
		{
			MethodName: "UndeleteFile",
			Handler:    _ClientMasterService_UndeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _ClientMasterService_RenameFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/client_master/client_master.proto",
}
